apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-world-view-deployments-role
  namespace: hello-world
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
